name: Bitrise CI

on:
  pull_request_review:
    types: [edited, submitted]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Bitrise Build
      env:
        build_token: ${{ secrets.BITRISE_BUILD_TOKEN }}
        app_id: ${{ secrets.BITRISE_APP_ID }}
        branch: ${{ github.event.pull_request.head.ref }}
      if: github.event.review.body == 'bitrise'
      run: curl https://app.bitrise.io/app/$app_id/build/start.json --data '{"hook_info":{"type":"bitrise","build_trigger_token":"'$build_token'"},"build_params":{"branch":"'$branch'"},"triggered_by":"curl"}'



