name: CI

on:
  pull_request_review:
    types: [edited, submitted]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      env:
        build_token: ${{ secrets.BITRISE_BUILD_TOKEN }}
        app_id: ${{ secrets.BITRISE_APP_ID }}
    - name: Trigger Bitrise Build
      run: curl https://app.bitrise.io/app/c032495a58efb653/build/start.json --data '{"hook_info":{"type":"bitrise","build_trigger_token":"YAHEpG5D1fft0Zy4ax5-aQ"},"build_params":{"branch":"test2"},"triggered_by":"curl"}'



